name: Continuous Integration

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build :
    env : 
      NEXT_DATOCMS_API_TOKEN: ${{secrets.NEXT_DATOCMS_API_TOKEN}}
      NEXT_DATOCMS_REVALIDATE_TOKEN : ${{secrets.NEXT_DATOCMS_REVALIDATE_TOKEN}}
      CI: false

    name : Build the Site
    runs-on : ubuntu-latest
    steps :
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
    # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install --frozen-lockfile
        
      - name : Build the Site
        run : npm run build

  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install --frozen-lockfile

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          eslint: true
          eslint_args: "--no-error-on-unmatched-pattern"
          eslint_auto_fix: true
          prettier: true
          prettier_auto_fix: true
